CREATE DATABASE WALLETS;
USE WALLETS;

CREATE TABLE WALLETS (
    WALLET_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL UNIQUE,	-- KHÔNG ĐỂ TRỐNG TRÙNG ID NGƯỜI DÙNG
    BALANCE DECIMAL(15,2) NOT NULL CHECK (BALANCE >= 0),	-- SỐ DƯ KHÔNG ÂM
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP	-- TỰ ĐỘNG ĐIỀN THỜI GIAN
);

CREATE TABLE WALLET_TRANSACTIONS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    WALLET_ID INT,
    STATUS_TRANSACTION TINYINT DEFAULT 0,	-- TRẠNG THÁI MẶC ĐỊNH LÀ 0 = KHÔNG HOÀN THÀNH (GÁN)
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	-- TỰ ĐỘNG ĐIỀN THỜI GIAN
    FOREIGN KEY (WALLET_ID)	-- LIÊN KẾT VỚI WALLETS
    REFERENCES WALLETS(WALLET_ID)
);