CREATE DATABASE CUSTOMERS;

USE CUSTOMERS;

CREATE TABLE CUSTOMERS (
    CUSTOMERID INT PRIMARY KEY,
    FULLNAME VARCHAR(100),
    EMAIL VARCHAR(100),
    AGE INT
);

ALTER TABLE CUSTOMERS
MODIFY FULLNAME VARCHAR(100) NOT NULL,	-- BẮT BUỘC KHÁCH HÀNG PHẢI CÓ TÊN
MODIFY EMAIL VARCHAR(100) NOT NULL,	-- KHÔNG CHO PHÉP EMAIL RỖNG
ADD CONSTRAINT UQ_EMAIL UNIQUE (EMAIL),	-- NGĂN EMAIL BỊ TRÙNG
ADD CONSTRAINT CHK_AGE CHECK (AGE >= 0);	-- KHÔNG CHO PHÉP TUỔI ÂM