CREATE DATABASE PRODUCTS;

USE PRODUCTS;

CREATE TABLE PRODUCTS (
    ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL, -- THÊM RÀNG BUỘC KHÔNG ĐƯỢC ĐỂ TRỐNG, TÊN SẢN PHẨM KHÔNG CẦN QUÁ DÀI NÊN RÚT TỪ 255 -> 100
    PRICE DECIMAL(10, 2) NOT NULL, -- GIÁ SẢN PHẨM THƯỜNG KHÔNG TỚI 18 CHỮ SỖ -> 10 ĐỂ TRÁNH TỐN BỘ NHỚ
    Description TEXT
);