CREATE DATABASE ORDER_MANAGEMENT;

USE ORDER_MANAGEMENT;

CREATE TABLE CUSTOMERS (
    CUSTOMERID INT PRIMARY KEY AUTO_INCREMENT,
    FULLNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    AGE INT CHECK(AGE >= 0)
);

CREATE TABLE ORDERS (
    ORDERID INT PRIMARY KEY AUTO_INCREMENT,
    ORDERDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOTALAMOUNT DECIMAL(10,2) NOT NULL CHECK (TOTALAMOUNT >= 0),
    CUSTOMERID INT,
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID)
);